name: Update GitHub Data

on:
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-gh-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Check formatting
        run: npm run format-check

      - name: Update GitHub data
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: node src/api/updateGHData.js

      - name: Update formatting
        run: npm run lint

      - name: Commit changes to ghdata.json
        run: |
          git config --global user.name "shuklabhay/portfolio"
          git config --global user.email "portfolio[bot]@shuklabhay.github.io"
          git add sitedata/ghdata.json
          git commit -m 'Update github data' || true
          git push
